// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz5oeF9cXrKspOGRDRUdJZvgFdd7P74G0',
    appId: '1:750213526967:web:e08485a73ba9ad1a62a432',
    messagingSenderId: '750213526967',
    projectId: 'sdsd-a3d61',
    authDomain: 'sdsd-a3d61.firebaseapp.com',
    storageBucket: 'sdsd-a3d61.firebasestorage.app',
    measurementId: 'G-PCTK4FVBWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvtsVO3u06NKHKkOM4YxhyLUzsN7TXFNs',
    appId: '1:750213526967:android:7675fb6291a89e5662a432',
    messagingSenderId: '750213526967',
    projectId: 'sdsd-a3d61',
    storageBucket: 'sdsd-a3d61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA30DE8oXNfCig8ttUrkhBBXEortTnOds',
    appId: '1:750213526967:ios:cd4c528486942b8d62a432',
    messagingSenderId: '750213526967',
    projectId: 'sdsd-a3d61',
    storageBucket: 'sdsd-a3d61.firebasestorage.app',
    iosBundleId: 'com.example.sdsd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA30DE8oXNfCig8ttUrkhBBXEortTnOds',
    appId: '1:750213526967:ios:cd4c528486942b8d62a432',
    messagingSenderId: '750213526967',
    projectId: 'sdsd-a3d61',
    storageBucket: 'sdsd-a3d61.firebasestorage.app',
    iosBundleId: 'com.example.sdsd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz5oeF9cXrKspOGRDRUdJZvgFdd7P74G0',
    appId: '1:750213526967:web:7369c1aaff6b63f062a432',
    messagingSenderId: '750213526967',
    projectId: 'sdsd-a3d61',
    authDomain: 'sdsd-a3d61.firebaseapp.com',
    storageBucket: 'sdsd-a3d61.firebasestorage.app',
    measurementId: 'G-WS1K4GJ95K',
  );
}
